export {default as Homepage} from "./Home"
export {default as Projects} from "./Projects"
export {default as Submission} from "./Submission"
export {default as Blog} from "./Blog"
export {default as Earn} from "./Earn"
export {default as KYC} from "./Kyc"
export {default as Roadmaps} from "./Roadmaps"